language: java
services: docker
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'

git:
  depth: false
  submodules: false

before_install:
  - echo SWTICH TO PYTHON3
  - pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip3 install ansible
  - echo UPDATE SUBMODULES
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - git submodule foreach "if [[ -f '.gitmodules' ]]; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; git submodule foreach update --init; fi"

install:
  - ls -l

#Create new project and build it to see if it works
script:
  - ./devops
