language: java

cache:
  directories:
    - ~/.m2/repository

git:
  depth: false
  submodules: false

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
  - echo SWTICH TO PYTHON3
  - pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip3 install virtualenv virtualenvwrapper workon
  - echo SETUP VIRTUALENV
  - which python3
  - which virtualenv
  - find / -name virtualenvwrapper.sh
  - export WORKON_HOME=$HOME/.virtualenvs
  - export PROJECT_HOME=$HOME/Devel
  - export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
  - export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
  - source /usr/local/bin/virtualenvwrapper.sh
  - echo UPDATE SUBMODULES
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - git submodule foreach "if [[ -f '.gitmodules' ]]; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; git submodule foreach update --init; fi"

install:
  - ls -l

#Create new project and build it to see if it works
script:
  - ./devops
