#!/bin/bash

USER_GIT_SIGNINGKEY=$(git config user.signingkey)
USER_GIT_EMAIL=$(git config user.email)

git pull

git lfs pull

#ATTACH HEADS if required
git submodule foreach '(git status | grep "HEAD detached") && git checkout master && git pull || true'

#SYNC MODULES
git submodule sync

#UPDATE MODULES and clone if needed
git submodule update --remote --init

#ATTACH HEADS if required
git submodule foreach '(git status | grep "HEAD detached") && git checkout master && git pull || true'

if [[ ! -z $USER_GIT_SIGNINGKEY && ! -z $USER_GIT_EMAIL ]]; then
    echo "Updating submodules signing key $USER_GIT_SIGNINGKEY and email $USER_GIT_EMAIL"
    git submodule foreach "git config user.signingkey $USER_GIT_SIGNINGKEY"
    git submodule foreach "git config user.email $USER_GIT_EMAIL"

fi

#git submodule foreach git pull