#!/bin/bash

GITSTATS=$(which gitinspector)

if [[ ! -z $GITSTATS ]]; then
    if [[ ! -d ".stats" ]]; then
        mkdir .stats
    fi
    git config diff.renameLimit 999999
    gitinspector -F htmlembedded -f **,*.*,.* -HTlrm  >.stats/$(basename "$PWD").html
    git submodule foreach 'git config diff.renameLimit 999999; gitinspector -F htmlembedded -f **,*.*,.* -HTlrm  >../.stats/$name.html; git config --unset diff.renameLimit'
    git config --unset diff.renameLimit
else
    echo "Please install gitinspector 'npm i -g gitinspector'"
fi